---
name: Continous Deployment

on:
  push:
    branches:
      - main
      - production
  pull_request: []

jobs:
  test:
    name: Test Run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

  lint:
    name: Lint Run
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-22.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Staging
        run: echo "Deploy to Staging..."

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-22.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Production
        run: echo "Deploy to Production..."