---
name: Continous Deployment

on: push

jobs:
  hello-gh-actions:
    name: Hello Actions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: echo "RUNNING TESTS"
